name: Build CI

on:
  push:
    tags-ignore:
      - "**"

jobs:
  build-win:
    strategy: 
      matrix: 
        os: [windows-latest]
        dotnet: [8.0.203]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ matrix.dotnet }}
          
      - name: restore nuget packages
        run: dotnet restore
        
      - name: build
        run: dotnet build
          
      - name: publish win-x64
        run: dotnet publish SMSL.UI -p:PublishProfile=win-x64.pubxml
        
      - name: upload artifact win-x64
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: build/win-x64
        
      - name: publish win-x86
        run: dotnet publish SMSL.UI -p:PublishProfile=win-x86.pubxml
        
      - name: upload artifact win-x86
        uses: actions/upload-artifact@v4
        with:
          name: win-x86
          path: build/win-x86
        
      - name: publish win-arm64
        run: dotnet publish SMSL.UI -p:PublishProfile=win-arm64.pubxml
        
      - name: upload artifact win-arm64
        uses: actions/upload-artifact@v4
        with:
          name: win-arm64
          path: build/win-arm64
          
  build-osx:
    strategy:
      matrix:
        os: [macos-latest]
        dotnet: [8.0.203]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: restore nuget packages
        run: dotnet restore
        
      - name: build
        run: dotnet build

      - name: publish osx-x64
        run: dotnet publish SMSL.UI -p:PublishProfile=osx-x64.pubxml

      - name: upload artifact osx-x64
        uses: actions/upload-artifact@v4
        with:
          name: osx-x64
          path: build/osx-x64

      - name: publish osx-arm64
        run: dotnet publish SMSL.UI -p:PublishProfile=osx-arm64.pubxml

      - name: upload artifact osx-arm64
        uses: actions/upload-artifact@v4
        with:
          name: osx-arm64
          path: build/osx-arm64
            
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [8.0.203]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: restore nuget packages
        run: dotnet restore
        
      - name: build
        run: dotnet build

      - name: publish linux-x64
        run: dotnet publish SMSL.UI -p:PublishProfile=linux-x64.pubxml

      - name: upload artifact linux-x64
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: build/linux-x64

      - name: publish linux-arm64
        run: dotnet publish SMSL.UI -p:PublishProfile=linux-arm64.pubxml

      - name: upload artifact linux-arm64
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: build/linux-arm64
          
  publish:
    if: github.repository_owner == 'erha134' && contains(github.event.head_commit.message, '[release]') == true && github.event_name == 'push'
    needs: [build-win, build-osx, build-linux]
    runs-on: ubuntu-latest
    
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        
      - name: read gradle.properties
        id: prop_info
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "version.properties"
          properties: "current_version"
        
      - name: publish
        uses: softprops/action-gh-release@v2
        with:
          name: "SMSL ${{ steps.prop_info.outputs.current_version }}"
          tag-name: "${{ steps.prop_info.outputs.current_version }}"
          files: |
            build/**/**.exe
            build/**/**.dmg
    