name: PR Check

on:
  pull_request:

jobs:
  check:
    strategy: 
      matrix: 
        os: [ubuntu-latest]
        dotnet: [8.0.203]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ matrix.dotnet }}
          
      - name: restore nuget packages
        run: dotnet restore
        
      - name: build
        run: dotnet build
